### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by marekdedic** [TooTallNate/node-agent-base#64]
Hi, I'm using `agent-base` in a GitHub action (as a transitive dependency of `@octokit/action.js`). It seems to work on my local computer, however when I run it in GA, I get the following error:

```
Error: Cannot find module '/home/runner/work/_actions/skaut/wordpress-version-checker/actions-github-script/node_modules/agent-base/dist/src/index'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:297:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/skaut/wordpress-version-checker/actions-github-script/node_modules/proxy-agent/index.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/runner/work/_actions/skaut/wordpress-version-checker/actions-github-script/node_modules/agent-base/package.json',
  requestPath: 'agent-base'
}
```

You can see the action [here](https://github.com/skaut/wordpress-version-checker/tree/actions-github-script) and a run in the test repo [here](https://github.com/marekdedic/wpvc-test/runs/4127709908?check_suite_focus=true).

**Comment by marekdedic** [comment]
Maybe this could be related? actions/github-script#68

**Comment by kswedberg** [comment]
I'm getting a similar error in vscode when I use a jsconfig.json file:
```
File '[…]/node_modules/agent-base/dist/src/index' not found.
  The file is in the program because:
    Root file specified for compilation
```

The only thing that fixes it for me is going into `node_modules/agent-base/package.json` and changing:

```
"main": "dist/src/index",
```

to 

```
"main": "dist/src/index.js",
```

@TooTallNate , I wonder if you would mind making that small change in your package.json? Manually changing it in my own project is an ephemeral solution at best because I don't source my `node_modules` directory.

thanks!

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
